services:
  - type: web
    name: lightwallet-engine
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DEFAULT_CURRENCY
        value: CREDIT
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_URL_SANDBOX
        sync: false
      - key: MASTER_ADMIN_KEY
        generateValue: true
